# Test configuration for nested AnyValidatorFilter

server:
  grpc_port: 9090
  http_port: 8080

trust_domain: "parsec.example.com"

exchange_server:
  claims_filter:
    type: stub

trust_store:
  type: filtered_store
  validators:
    - name: validator-1
      type: stub_validator
  
  # Nested any filters
  filter:
    type: any
    filters:
      # Allow if actor is admin
      - type: cel
        script: actor.claims.admin == true
      
      # OR allow if any of these nested conditions match
      - type: any
        filters:
          - type: cel
            script: actor.trust_domain == "prod.example.com"
          - type: cel
            script: validator_name == "validator-1"

data_sources: []

issuers:
  - token_type: "urn:ietf:params:oauth:token-type:txn_token"
    type: stub
    issuer_url: "https://parsec.example.com"
    ttl: 5m
    transaction_context:
      - type: passthrough
    request_context:
      - type: request_attributes
