# parsec Configuration - Minimal Example
#
# Simplest possible configuration for getting started
# Uses all stub/default implementations

server:
  grpc_port: 9090
  http_port: 8080

trust_domain: "parsec.example.com"

trust_store:
  type: stub_store
  validators:
    - type: stub_validator

data_sources: []

claim_mappers:
  transaction_context:
    - type: passthrough
  request_context:
    - type: request_attributes

issuers:
  - token_type: transaction_token
    type: stub
    issuer_url: "https://parsec.example.com"
    ttl: 5m

claims_filter:
  type: stub

