# parsec Configuration - Minimal Example (TOML format)

trust_domain = "parsec.example.com"

[server]
grpc_port = 9090
http_port = 8080

[exchange_server.claims_filter]
type = "stub"

[trust_store]
type = "stub_store"

[[trust_store.validators]]
type = "stub_validator"
credential_types = ["bearer"]

[[issuers]]
token_type = "urn:ietf:params:oauth:token-type:txn_token"
type = "stub"
issuer_url = "https://parsec.example.com"
ttl = "5m"

[[issuers.transaction_context]]
type = "passthrough"

[[issuers.request_context]]
type = "request_attributes"
