# Test configuration for AnyValidatorFilter

server:
  grpc_port: 9090
  http_port: 8080

trust_domain: "parsec.example.com"

trust_store:
  type: filtered_store
  validators:
    - name: prod-validator
      type: stub_validator
      credential_types: ["bearer"]
    - name: dev-validator
      type: stub_validator
      credential_types: ["bearer"]
    - name: admin-validator
      type: stub_validator
      credential_types: ["bearer"]
  
  # Allow access if ANY of these conditions match
  filter:
    type: any
    filters:
      # Allow if actor is from prod trust domain
      - type: cel
        script: actor.trust_domain == "prod.example.com"
      
      # Allow if actor has admin claim
      - type: cel
        script: actor.claims.admin == true
      
      # Always allow dev-validator for testing
      - type: cel
        script: validator_name == "dev-validator"

data_sources: []

claim_mappers:
  transaction_context:
    - type: passthrough
  request_context:
    - type: request_attributes

issuers:
  - token_type: transaction_token
    type: stub
    issuer_url: "https://parsec.example.com"
    ttl: 5m

claims_filter:
  type: stub

